#!/usr/bin/env bash
#
# DBP Bahasa Melayu Advisory Chatbot - one-command deployment
# AMD / GMKtec (Radeon iGPU, Vulkan backend) - no LM Studio, no ROCm, no CUDA.
#
#   ./deploy.sh          full deploy (preflight -> build -> start -> verify)
#   ./deploy.sh check    preflight only, changes nothing
#   ./deploy.sh status   show what is running
#   ./deploy.sh logs     follow logs
#   ./deploy.sh stop     stop THIS project only
#
# Safe to re-run. Never modifies the host: no usermod, no Docker daemon edits,
# no driver installs, and it only ever touches its own Compose project.

set -euo pipefail

PROJECT="dbp-chatbot"
EXPECTED_DOCS=33320
COLLECTION="dbp_khidmatnasihat_clean_atomic"
cd "$(dirname "$0")"

RED=$'\e[31m'; GRN=$'\e[32m'; YLW=$'\e[33m'; BLU=$'\e[34m'; BLD=$'\e[1m'; RST=$'\e[0m'
ok()   { echo "  ${GRN}OK${RST}    $*"; }
warn() { echo "  ${YLW}WARN${RST}  $*"; }
die()  { echo "  ${RED}STOP${RST}  $*" >&2; exit 1; }
step() { echo; echo "${BLU}${BLD}==> $*${RST}"; }

dc() { docker compose -p "$PROJECT" "$@"; }

# ---------------------------------------------------------------- preflight --
preflight() {
  step "Preflight - checking this machine (nothing is changed)"

  command -v docker >/dev/null 2>&1 || die "Docker is not installed. Ask faculty IT; do not install it yourself on a shared server."
  docker compose version >/dev/null 2>&1 || die "The 'docker compose' plugin is missing. Ask faculty IT."
  docker info >/dev/null 2>&1 || die "Cannot talk to the Docker daemon. You may need to be in the 'docker' group: sudo usermod -aG docker \$USER (then log out and back in)."
  ok "Docker $(docker --version | awk '{print $3}' | tr -d ,) + Compose $(docker compose version --short 2>/dev/null || echo present)"

  # GPU device nodes. Without these llama.cpp silently falls back to the CPU
  # software renderer (llvmpipe) and generation becomes unusably slow.
  [ -e /dev/kfd ] || die "/dev/kfd is missing - the amdgpu driver is not active. Ask faculty IT to confirm the driver is loaded. Do NOT install ROCm."
  [ -d /dev/dri ] || die "/dev/dri is missing - no GPU device nodes. Ask faculty IT."
  ok "GPU device nodes present: /dev/kfd and /dev/dri ($(ls /dev/dri | grep -c render) render node(s))"

  # Knowledge base must sit at exactly this path or Chroma opens an empty DB.
  [ -f data/chroma_db/chroma.sqlite3 ] \
    || die "data/chroma_db/chroma.sqlite3 not found. You are either in the wrong folder, or the DB is nested one level too deep (data/chroma_db/chroma_db/). Fix the folder level before continuing."
  ok "ChromaDB present ($(du -h data/chroma_db/chroma.sqlite3 | cut -f1))"

  for f in Dockerfile docker-compose.yml requirements.txt frontend/package.json frontend/package-lock.json; do
    [ -f "$f" ] || die "$f is missing - this is not a complete deployment folder."
  done
  ok "Deployment folder looks complete"

  local available_gb
  available_gb="$(df -BG --output=avail . 2>/dev/null | tail -1 | tr -dc '0-9')"
  if [ "${available_gb:-0}" -ge 14 ]; then
    ok "Disk space looks sufficient"
  else
    warn "Less than 14 GB free. The build, Qwen3 model and caches may not fit."
  fi
}

# ------------------------------------------------------- machine-specific env --
# The GPU group IDs are NOT portable. They differ between machines and Ubuntu
# releases, and wrong values are the single most common cause of "the GPU is
# not detected" on a new server. Always derive them from the target machine.
write_env() {
  step "Configuring .env for THIS machine"

  local render_gid video_gid port
  render_gid="$(getent group render | cut -d: -f3 || true)"
  video_gid="$(getent group video  | cut -d: -f3 || true)"
  [ -n "$render_gid" ] || die "No 'render' group on this machine. Ask faculty IT to confirm the amdgpu driver is installed."
  [ -n "$video_gid" ]  || die "No 'video' group on this machine. Ask faculty IT."

  # Keep the operator's chosen port if .env already exists, else default.
  port="$(grep -sE '^CHATBOT_HOST_PORT=' .env | cut -d= -f2 || true)"
  port="${port:-18501}"

  # If that port is taken by something else, step to the next free one rather
  # than colliding with another faculty application on this shared server.
  # A port held by our OWN already-running chatbot does not count as a clash,
  # otherwise every re-run would drift to a new port.
  local ours=""
  ours="$(docker ps --filter "name=^${PROJECT}$" --format '{{.Ports}}' 2>/dev/null || true)"
  if ss -ltn 2>/dev/null | grep -q ":${port} " && ! grep -q ":${port}->" <<<"$ours"; then
    local original="$port"
    while ss -ltn 2>/dev/null | grep -q ":${port} "; do port=$((port + 1)); done
    warn "Port ${original} is already in use by another application - using ${port} instead"
  fi

  cat > .env <<ENV_EOF
# Generated by deploy.sh for this machine. Re-run ./deploy.sh to regenerate.

CHROMA_PERSIST_DIR=/app/data/chroma_db
CHROMA_COLLECTION_NAME=${COLLECTION}

# Points at the llama.cpp Vulkan container over the private Docker network.
# The LMSTUDIO_* names are kept only for compatibility with the existing app
# code - there is no LM Studio in this architecture.
LMSTUDIO_BASE_URL=http://llm:8080/v1/
LMSTUDIO_MODEL=Qwen/Qwen3-8B
LMSTUDIO_TIMEOUT_S=120

# Retrieval/reranking stay on CPU. Only the LLM uses the GPU.
RAG_DEVICE=cpu
RAG_USE_FP16=false

# Retrieval policy (override only after measuring an evaluation set).
RAG_K_SMALL=15
RAG_K_LARGE=40
RAG_FINAL_N=6
RAG_MIN_KEEP_SCORE=0.8
RAG_EXPAND_SCORE=1.5
RAG_HYDE_SCORE=1.0
RAG_ANSWER_SCORE=0.8

# GGUF model pulled by llama.cpp on first start.
LLAMA_HF_REPO=Qwen/Qwen3-8B-GGUF:Q5_K_M

# React/FastAPI port published to the host.
CHATBOT_HOST_PORT=${port}

# AMD GPU passthrough - DETECTED ON THIS MACHINE, do not copy between servers.
RENDER_GID=${render_gid}
VIDEO_GID=${video_gid}
ENV_EOF

  ok "GPU groups detected: render=${render_gid} video=${video_gid}"
  ok "Chatbot port: ${port}"
}

# ------------------------------------------------------------------ deploy --
main() {
  preflight
  write_env
  local port; port="$(grep -E '^CHATBOT_HOST_PORT=' .env | cut -d= -f2)"

  step "Pulling the llama.cpp Vulkan image"
  dc pull llm

  step "Building the chatbot image (first build takes several minutes)"
  dc build chatbot

  step "Starting the LLM container"
  dc up -d llm
  echo "  Waiting for the model to load (first run downloads ~5.9 GB of GGUF)..."
  local waited=0
  until docker run --rm --network "${PROJECT}_dbp-internal" curlimages/curl:latest \
          -fsS http://llm:8080/v1/models >/dev/null 2>&1; do
    [ "$waited" -ge 900 ] && die "The LLM did not become ready within 15 minutes. Check: docker compose -p ${PROJECT} logs llm"
    sleep 10; waited=$((waited + 10))
    [ $((waited % 60)) -eq 0 ] && echo "  ...still loading (${waited}s)"
  done
  ok "LLM is serving on the private network"

  # Confirm a real GPU is visible, not the llvmpipe software renderer.
  #
  # Do NOT grep the server log for this. Recent llama.cpp builds no longer print
  # the "ggml_vulkan: Found N Vulkan devices" banner that older guides tell you
  # to look for, so a log grep gives a false alarm on a perfectly good machine.
  # Asking the binary directly works on every build.
  local devices
  devices="$(docker run --rm --device=/dev/dri --device=/dev/kfd \
      --group-add "$(getent group render | cut -d: -f3)" \
      --group-add "$(getent group video | cut -d: -f3)" \
      --entrypoint /app/llama-server ghcr.io/ggml-org/llama.cpp:server-vulkan \
      --list-devices 2>/dev/null | grep -i vulkan || true)"

  if [ -z "$devices" ]; then
    warn "No Vulkan GPU is visible to Docker - llama.cpp will fall back to the CPU and answers will be very slow."
    warn "Check /dev/dri passthrough and the RENDER_GID/VIDEO_GID values in .env."
  elif grep -qi "llvmpipe" <<<"$devices"; then
    warn "Only llvmpipe (CPU software rendering) is available, NOT the real GPU."
    warn "Ask faculty IT to confirm the amdgpu driver is loaded. Do NOT install ROCm."
  else
    ok "GPU visible: $(sed 's/^ *//' <<<"$devices" | head -1)"
  fi

  step "Verifying the knowledge base"
  dc run --rm --no-deps chatbot python /app/verify_chroma.py \
    || die "ChromaDB verification failed. Expected ${EXPECTED_DOCS} documents in ${COLLECTION}. Do NOT rebuild or re-embed the knowledge base - fix the data folder path instead."

  step "Starting the chatbot"
  dc up -d
  echo "  Waiting for the React/FastAPI application..."
  waited=0
  until curl -fsS "http://127.0.0.1:${port}/api/health" >/dev/null 2>&1; do
    [ "$waited" -ge 180 ] && die "The chatbot did not come up. Check: docker compose -p ${PROJECT} logs chatbot"
    sleep 5; waited=$((waited + 5))
  done

  step "Deployment complete"
  dc ps --format "table {{.Name}}\t{{.Status}}"
  echo
  echo "  ${BLD}Open:${RST} http://localhost:${port}"
  echo
  echo "  On a headless server, tunnel from your own laptop instead of exposing the port:"
  echo "    ssh -L ${port}:localhost:${port} $USER@$(hostname -I | awk '{print $1}')"
  echo
  echo "  Logs:   ./deploy.sh logs"
  echo "  Stop:   ./deploy.sh stop"
}

case "${1:-deploy}" in
  deploy) main ;;
  check)  preflight; echo; echo "  Preflight passed. Run ./deploy.sh to deploy." ;;
  status) dc ps ;;
  logs)   dc logs -f --tail=100 ;;
  stop)   dc down; echo "  Stopped. The model cache volume was kept (use 'down -v' to delete it)." ;;
  *)      die "Unknown command '${1}'. Use: deploy | check | status | logs | stop" ;;
esac
